import type { LevelConfig } from "@/types/game";

export const LEVELS: LevelConfig[] = [
  {
    level: 1,
    playerSpeed: 7.2,
    roadSpeed: 155,
    obstacleSpeed: 150,
    obstacleSpawnRate: 1.25,
    obstacleCount: 1,
    obstacleTypes: ["cone", "slow-car"],
    requiredSurvivalTime: 22,
    scoreMultiplier: 1,
    winScoreTarget: 520,
  },
  {
    level: 2,
    playerSpeed: 7.5,
    roadSpeed: 175,
    obstacleSpeed: 170,
    obstacleSpawnRate: 1.12,
    obstacleCount: 1,
    obstacleTypes: ["cone", "slow-car", "barrel"],
    requiredSurvivalTime: 25,
    scoreMultiplier: 1.15,
    winScoreTarget: 680,
  },
  {
    level: 3,
    playerSpeed: 7.8,
    roadSpeed: 195,
    obstacleSpeed: 190,
    obstacleSpawnRate: 1.02,
    obstacleCount: 2,
    obstacleTypes: ["cone", "slow-car", "barrel"],
    requiredSurvivalTime: 28,
    scoreMultiplier: 1.3,
    winScoreTarget: 850,
  },
  {
    level: 4,
    playerSpeed: 8,
    roadSpeed: 215,
    obstacleSpeed: 215,
    obstacleSpawnRate: 0.94,
    obstacleCount: 2,
    obstacleTypes: ["cone", "truck", "barrel"],
    requiredSurvivalTime: 31,
    scoreMultiplier: 1.45,
    winScoreTarget: 1060,
  },
  {
    level: 5,
    playerSpeed: 8.2,
    roadSpeed: 240,
    obstacleSpeed: 240,
    obstacleSpawnRate: 0.86,
    obstacleCount: 2,
    obstacleTypes: ["slow-car", "truck", "barrel"],
    requiredSurvivalTime: 34,
    scoreMultiplier: 1.65,
    winScoreTarget: 1320,
  },
  {
    level: 6,
    playerSpeed: 8.4,
    roadSpeed: 265,
    obstacleSpeed: 268,
    obstacleSpawnRate: 0.8,
    obstacleCount: 3,
    obstacleTypes: ["cone", "slow-car", "truck", "barrel"],
    requiredSurvivalTime: 37,
    scoreMultiplier: 1.85,
    winScoreTarget: 1620,
  },
  {
    level: 7,
    playerSpeed: 8.7,
    roadSpeed: 292,
    obstacleSpeed: 298,
    obstacleSpawnRate: 0.74,
    obstacleCount: 3,
    obstacleTypes: ["slow-car", "truck", "barrel", "oil"],
    requiredSurvivalTime: 40,
    scoreMultiplier: 2.05,
    winScoreTarget: 1960,
  },
  {
    level: 8,
    playerSpeed: 9,
    roadSpeed: 320,
    obstacleSpeed: 330,
    obstacleSpawnRate: 0.68,
    obstacleCount: 3,
    obstacleTypes: ["cone", "truck", "barrel", "oil"],
    requiredSurvivalTime: 43,
    scoreMultiplier: 2.25,
    winScoreTarget: 2350,
  },
  {
    level: 9,
    playerSpeed: 9.3,
    roadSpeed: 350,
    obstacleSpeed: 365,
    obstacleSpawnRate: 0.62,
    obstacleCount: 4,
    obstacleTypes: ["slow-car", "truck", "barrel", "oil"],
    requiredSurvivalTime: 46,
    scoreMultiplier: 2.5,
    winScoreTarget: 2820,
  },
  {
    level: 10,
    playerSpeed: 9.6,
    roadSpeed: 385,
    obstacleSpeed: 405,
    obstacleSpawnRate: 0.56,
    obstacleCount: 4,
    obstacleTypes: ["cone", "slow-car", "truck", "barrel", "oil"],
    requiredSurvivalTime: 50,
    scoreMultiplier: 2.85,
    winScoreTarget: 3450,
  },
];

export function getLevelConfig(level: number) {
  return LEVELS.find((item) => item.level === level) ?? LEVELS[0];
}
